#yaml 配置实例
version: '3'
services:
  php:
    container_name: php7.4
    image: php:7.4-fpm
    restart: always
    privileged: true
    ports:
      - "9000:9000"
    volumes:
      - "/data/www:/var/www" # php代码目录
      - "/data/docker/develop_php/php/php.ini:/usr/local/etc/php/php.ini" # php配置文件目录
  nginx:
    container_name: nginx
    image: nginx:latest
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "php"
    volumes:
      - "/data/www:/var/www" # php代码目录
      - "/data/docker/develop_php/nginx/logs:/var/log/nginx" # nginx日志文件
      - "/data/docker/develop_php/nginx/nginx.conf:/etc/nginx/nginx.conf" # nginx配置文件目录
      - "/data/docker/develop_php/nginx/conf.d:/etc/nginx/conf.d" # nginx虚拟主机配置文件目录